### PR TITLE
[WIP] Add LXC support through nova-multi-compute-lxc role

### PR DESCRIPTION
**Pull request by vuntz**
Tested with
http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-rootfs.img.gz

### CODE REVIEW

**Comment by vuntz** [comment]
Note: we need to set `uid_maps` and `gid_maps` in nova.conf to avoid this:

> Running libvirt-lxc without user namespaces is dangerous. Containers spawned by Nova will be run as the host's root user. It is highly suggested that user namespaces be used in a public or multi-tenant environment.

**Comment by tboerger** [comment]
LGTM

**Comment by mjura** [comment]
:+1:

**Comment by rsalevsky** [comment]
@vuntz, this repository got merged into [crowbar-openstack](https://github.com/crowbar/crowbar-openstack).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by vuntz** [comment]
Won't be used.

**Pull request closed without merging**
