### PR TITLE
Split recipes in nova-compute-hyperv role

### PR DESCRIPTION
**Pull request by jsuchome**
We split the the setup recipe in the hyperv cookbook in two seperate
recipes do_setup and do_nova to make the basic setup recipe usable for
other cookbooks too.

(Backport of https://github.com/crowbar/barclamp-nova/pull/451. Requires relevant change in hyperv cookbook as well.)

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by tboerger** [comment]
+1

**Comment by nkrinner** [comment]
Also needs a `cherry-pick -x`

**Comment by nkrinner** [comment]
see https://github.com/crowbar/barclamp-nova/pull/455

**Comment by nkrinner** [comment]
I can't close this pr.

**Pull request closed without merging**
