### PR TITLE
Introduce HoundCI

### PR DESCRIPTION
**Pull request by rsalevsky**
We want to test HoundCI, this configs are needed to run Hound with
our preferred styles.

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:
I'm merging it as we already have it for barclamp-crowbar and it doesn't change the functionality.

**Comment by vuntz** [comment]
I thought we wanted to wait a couple of days to see how it works with barclamp-crowbar?

**Comment by rsalevsky** [comment]
@vuntz Yep but the most of us doesn't contribute to the crowbar barclamp. We want to extent the test a little bit to get a better overview.

**Comment by tboerger** [comment]
> I thought we wanted to wait a couple of days to see how it works with barclamp-crowbar?

We enabled just 2 repos for now to get a little bit more feedback.

**Pull request merged**
