### PR TITLE
Allocate a public IP for compute host if DVR is enabled

### PR DESCRIPTION
**Pull request by vuntz**
This is a requirement for DVR, see slide 4 of
http://fr.slideshare.net/carlbaldwin/dvr-slides

### CODE REVIEW

**Comment by mjura** [comment]
Looks OK :+1:

**Comment by rsalevsky** [comment]
:+1:

**Comment by rossella** [comment]
@vuntz was that so easy? so now the compute host is connected to the public network? nice :)

**Comment by vuntz** [comment]
@rhafer I just realized something: do you agree that https://github.com/crowbar/barclamp-nova/pull/443/files#diff-b5d70df618b0c2021467b57b8029e9b8R187 is totally wrong and should not be for all nodes but for compute nodes?

**Comment by jsuchome** [comment]
+1

**Comment by rhafer** [comment]
> @rhafer I just realized something: do you agree that …

Yes, that's true. Actually I think it's also wrong to do it for hyperV and VMware compute nodes.

**Comment by rhafer** [comment]
+1 (but needs to be merged together with: https://github.com/crowbar/barclamp-neutron/pull/210)

**Comment by vuntz** [comment]
The comment about all nodes getting IP addresses allocated is being handled in https://github.com/crowbar/barclamp-nova/pull/444

**Pull request merged**
