### PR TITLE
If tempest is deployed, load docker image at docker compute node

### PR DESCRIPTION
**Pull request by jsuchome**
so that tempest could run tests with docker based image.

The image is packaged in tempest barclamp. We can't do this from
tempest recipe because tempest might be deployed on another node
which does not have access to the docker comput node.

This solution is based on @vuntz 's proposal in https://github.com/crowbar/barclamp-tempest/pull/159

This should come together with https://github.com/crowbar/barclamp-tempest/pull/167 [EDIT]

### CODE REVIEW

**Comment by dirkmueller** [comment]
phew.. there is no way for glance to hand over the image to docker? this sounds fairly odd.. how is a user supposed to run docker containers ?

**Comment by jsuchome** [comment]
Unfortunately, this is the way it is. User is supposed to do docker pulls manually, together with creating glance images

**Comment by ovisan** [comment]
:+1:  tested and it works

**Comment by aplanas** [comment]
+1

**Pull request merged**
