### PR TITLE
Do not merge yet - Split recipes in nova-compute-hyperv role

### PR DESCRIPTION
**Pull request by nkrinner**
We split the the setup recipe in the hyperv cookbook in two seperate
recipes do_setup and do_nova to make the basic setup recipe usable for
other cookbooks too.

**Note:** Depends on https://github.com/crowbar/barclamp-hyperv-compute/pull/32

### CODE REVIEW

**Comment by jsuchome** [comment]
+1

**Comment by ovisan** [comment]
+1

**Comment by vuntz** [comment]
+1 once we're fine with the hyperv PR.

**Comment by tboerger** [comment]
:+1:

**Comment by mjura** [comment]
:+1:

**Pull request merged**
