### PR TITLE
allow neutron+glance+cinder to work with ssl-keystone (bnc#895594)

### PR DESCRIPTION
**Pull request by bmwiedemann**
This is needed when keystone is deployed with SSL certs
that dont cover all internal hostnames (aka insecure),
but one of the other services is not deployed with HTTPS,
so the insecure flag is missing there.

https://bugzilla.suse.com/show_bug.cgi?id=895594

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
I'd very much prefer to not change the template, but the value of the template variable in the recipe.

**Comment by bmwiedemann** [comment]
updated to change template vars

**Comment by toabctl** [comment]
+1

**Comment by rhafer** [comment]
+1

**Comment by bmwiedemann** [comment]
test on crowbarg12 looks good.

**Pull request merged**
